

import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class DeleteRecord extends javax.swing.JFrame {

    /**
     * Creates new form DeleteRecord
     */
    public DeleteRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainbadge = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        recordid = new javax.swing.JLabel();
        recordidfield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        customerid = new javax.swing.JLabel();
        metercount = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        customeridfield = new javax.swing.JTextField();
        metercountfield = new javax.swing.JTextField();
        descriptionfield = new javax.swing.JTextField();
        statusfield = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebuttob = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainbadge.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainbadge.setText("Delete Record");
        getContentPane().add(mainbadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 274, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete data.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 120, -1));

        recordid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recordid.setText("Record ID");
        getContentPane().add(recordid, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, -1));

        recordidfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        recordidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordidfieldActionPerformed(evt);
            }
        });
        getContentPane().add(recordidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 250, -1));

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, -1, -1));

        customerid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerid.setText("Customer ID");
        getContentPane().add(customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        metercount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        metercount.setText("Meter Count");
        getContentPane().add(metercount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, -1));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setText("Status");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, -1));

        customeridfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(customeridfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 287, -1));

        metercountfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        metercountfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metercountfieldActionPerformed(evt);
            }
        });
        getContentPane().add(metercountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 287, -1));

        descriptionfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(descriptionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 287, -1));

        statusfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(statusfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 287, -1));

        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 70, -1));

        resetbutton.setText("Reset");
        resetbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 70, -1));

        closebuttob.setText("Close");
        closebuttob.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closebuttob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttobActionPerformed(evt);
            }
        });
        getContentPane().add(closebuttob, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 670, 60, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jPanel2.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttobActionPerformed
setVisible(false);    }//GEN-LAST:event_closebuttobActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed

new DeleteRecord().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
String rid = recordidfield.getText();
try{
    Connection con =ConnectionProvider.getCon();
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery("select * from record where rid='"+rid+"'");
    if(rs.next()){
        customeridfield.setText(rs.getString(2));
        metercountfield.setText(rs.getString(3));
        descriptionfield.setText(rs.getString(4));
        statusfield.setText(rs.getString(5));
        
        
        
    }else{
        JOptionPane.showMessageDialog(null, "Record id doesnot exist");
    }
}catch(Exception e){
    JOptionPane.showMessageDialog(null, "Record id doesnot exist");
}
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
       String rid = recordidfield.getText();
       int a = JOptionPane.showConfirmDialog(null, "Do you want to delete","Select",JOptionPane.YES_NO_OPTION);
       if (a==0){
           try{
               Connection con =ConnectionProvider.getCon();
    Statement st = con.createStatement();
    st.executeUpdate("delete from record where rid='"+rid+"'");
    setVisible(false);
    new DeleteRecord().setVisible(true);
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e.getMessage());
           }
       }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void recordidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordidfieldActionPerformed
       this.searchbuttonActionPerformed(evt);
    }//GEN-LAST:event_recordidfieldActionPerformed

    private void metercountfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metercountfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metercountfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebuttob;
    private javax.swing.JLabel customerid;
    private javax.swing.JTextField customeridfield;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel description;
    private javax.swing.JTextField descriptionfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mainbadge;
    private javax.swing.JLabel metercount;
    private javax.swing.JTextField metercountfield;
    private javax.swing.JLabel recordid;
    private javax.swing.JTextField recordidfield;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusfield;
    // End of variables declaration//GEN-END:variables
}
