

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class DeleteCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public DeleteCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        mainbadge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namefirst = new javax.swing.JLabel();
        namemiddle = new javax.swing.JLabel();
        namelast = new javax.swing.JLabel();
        emaill = new javax.swing.JLabel();
        kebelee = new javax.swing.JLabel();
        contactt = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        middlenamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        cityy = new javax.swing.JLabel();
        zonee = new javax.swing.JLabel();
        homenumberr = new javax.swing.JLabel();
        hnfield = new javax.swing.JTextField();
        kebelefield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        zonefield = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        sex = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add customer.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setUndecorated(true);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainbadge.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainbadge.setText("Delete Customer");
        getContentPane().add(mainbadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 420, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        namefirst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namefirst.setText("First Name");
        getContentPane().add(namefirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 20));

        namemiddle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namemiddle.setText("Middle Name");
        getContentPane().add(namemiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, 20));

        namelast.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelast.setText("Last Name");
        getContentPane().add(namelast, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, 20));

        emaill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaill.setText("E-mail");
        getContentPane().add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 50, 20));

        kebelee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kebelee.setText("Kebele");
        getContentPane().add(kebelee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 55, 20));

        contactt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactt.setText("Contact");
        getContentPane().add(contactt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 20));

        firstnamefield.setForeground(new java.awt.Color(153, 153, 153));
        firstnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusLost(evt);
            }
        });
        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 277, 30));

        middlenamefield.setForeground(new java.awt.Color(153, 153, 153));
        middlenamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        middlenamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusLost(evt);
            }
        });
        middlenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(middlenamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 262, 277, 30));

        lastnamefield.setForeground(new java.awt.Color(153, 153, 153));
        lastnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusLost(evt);
            }
        });
        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 277, 30));

        emailfield.setForeground(new java.awt.Color(153, 153, 153));
        emailfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfieldFocusLost(evt);
            }
        });
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 277, 30));

        contactfield.setForeground(new java.awt.Color(153, 153, 153));
        contactfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactfieldFocusLost(evt);
            }
        });
        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 277, 30));

        deletebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 70, 30));

        resetbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 70, 30));

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 674, 60, 30));

        cityy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityy.setText("City");
        getContentPane().add(cityy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 43, 20));

        zonee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        zonee.setText("Zone");
        getContentPane().add(zonee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 43, 20));

        homenumberr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homenumberr.setText("Home Number");
        getContentPane().add(homenumberr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, 20));

        hnfield.setForeground(new java.awt.Color(153, 153, 153));
        hnfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hnfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hnfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hnfieldFocusLost(evt);
            }
        });
        hnfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hnfieldActionPerformed(evt);
            }
        });
        getContentPane().add(hnfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 277, 30));

        kebelefield.setForeground(new java.awt.Color(153, 153, 153));
        kebelefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kebelefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kebelefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kebelefieldFocusLost(evt);
            }
        });
        kebelefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebelefieldActionPerformed(evt);
            }
        });
        getContentPane().add(kebelefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 277, 30));

        cityfield.setForeground(new java.awt.Color(153, 153, 153));
        cityfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityfieldFocusLost(evt);
            }
        });
        cityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 277, 30));

        zonefield.setForeground(new java.awt.Color(153, 153, 153));
        zonefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        zonefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zonefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zonefieldFocusLost(evt);
            }
        });
        zonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonefieldActionPerformed(evt);
            }
        });
        getContentPane().add(zonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 277, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete user.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 130, 110));

        contactlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactlabel.setText("Contact ");
        getContentPane().add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, 20));

        searchbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, -1, -1));

        searchfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 250, -1));

        sex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sex.setText("Gender");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 50, 20));

        genderfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        genderfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderfieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 277, 30));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        jPanel2.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed

    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed

    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactfieldActionPerformed

    private void kebelefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebelefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebelefieldActionPerformed

    private void zonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonefieldActionPerformed

    private void firstnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusGained
                if(firstnamefield.getText().equals("Enter First Name")){
            firstnamefield.setText("");
        firstnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_firstnamefieldFocusGained

    private void firstnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusLost
                 if(firstnamefield.getText().equals("")){
            firstnamefield.setText("Enter First Name");
        firstnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_firstnamefieldFocusLost

    private void middlenamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusGained
        // TODO add your handling code here:
        if(middlenamefield.getText().equals("Enter Middle Name")){
            middlenamefield.setText("");
        middlenamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_middlenamefieldFocusGained

    private void middlenamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusLost
        // TODO add your handling code here:                 
        if(middlenamefield.getText().equals("")){
            middlenamefield.setText("Enter Middle Name");
        middlenamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_middlenamefieldFocusLost

    private void lastnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusGained
        // TODO add your handling code here:
        if(lastnamefield.getText().equals("Enter Last Name")){
            lastnamefield.setText("");
        lastnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_lastnamefieldFocusGained

    private void lastnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusLost
        // TODO add your handling code here:
                         if(lastnamefield.getText().equals("")){
            lastnamefield.setText("Enter Last Name");
        lastnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_lastnamefieldFocusLost

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        // TODO add your handling code here:
        if(emailfield.getText().equals("example@aait.com")){
            emailfield.setText("");
        emailfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emailfieldFocusGained

    private void emailfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusLost
        // TODO add your handling code here:
                         if(emailfield.getText().equals("")){
            emailfield.setText("example@aait.com");
        emailfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailfieldFocusLost

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        // TODO add your handling code here:
        if(contactfield.getText().equals("+251111111111")){
            contactfield.setText("");
        contactfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_contactfieldFocusGained

    private void contactfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusLost
        // TODO add your handling code here:
                         if(contactfield.getText().equals("")){
            contactfield.setText("+251111111111");
        contactfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_contactfieldFocusLost

    private void hnfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hnfieldFocusGained
        // TODO add your handling code here:
        if(hnfield.getText().equals("225")){
            hnfield.setText("");
        hnfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_hnfieldFocusGained

    private void hnfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hnfieldFocusLost
        // TODO add your handling code here:
                         if(hnfield.getText().equals("")){
            hnfield.setText("225");
        hnfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_hnfieldFocusLost

    private void kebelefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kebelefieldFocusGained
        // TODO add your handling code here:
        if(kebelefield.getText().equals("05")){
            kebelefield.setText("");
        kebelefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_kebelefieldFocusGained

    private void kebelefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kebelefieldFocusLost
        // TODO add your handling code here:
                         if(kebelefield.getText().equals("")){
            kebelefield.setText("05");
        kebelefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_kebelefieldFocusLost

    private void cityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusGained
        // TODO add your handling code here:
        if(cityfield.getText().equals("Hawassa")){
            cityfield.setText("");
        cityfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cityfieldFocusGained

    private void cityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusLost
        // TODO add your handling code here:
                         if(cityfield.getText().equals("")){
            cityfield.setText("Hawassa");
        cityfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_cityfieldFocusLost

    private void zonefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zonefieldFocusGained
        // TODO add your handling code here:
        if(zonefield.getText().equals("Sidama")){
            zonefield.setText("");
        zonefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_zonefieldFocusGained

    private void zonefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zonefieldFocusLost
        // TODO add your handling code here:
                         if(zonefield.getText().equals("")){
            zonefield.setText("Sidama");
        zonefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_zonefieldFocusLost

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
setVisible(false);
new DeleteCustomer().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void middlenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenamefieldActionPerformed

    private void hnfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hnfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hnfieldActionPerformed

    private void cityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityfieldActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
int a = JOptionPane.showConfirmDialog(null,"Do you want to delete","Select", JOptionPane.YES_NO_OPTION);
if(a==0){
        String contact = searchfield.getText();
try{
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from customer where contactnumber='"+contact+"';");
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
        setVisible(false);
        new DeleteCustomer().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } }     
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void genderfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderfieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        this.searchfieldActionPerformed(evt);       // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
String contact1 = searchfield.getText();
try{
Connection con = ConnectionProvider.getCon();
Statement st = con.createStatement();
ResultSet rs = st.executeQuery("select * from customer where contactnumber = '"+contact1+"'");
if (rs.next()){
    firstnamefield.setText(rs.getString(1));
    middlenamefield.setText(rs.getString(2));
    lastnamefield.setText(rs.getString(3));
    emailfield.setText(rs.getString(5));
    hnfield.setText(rs.getString(6));
    contactfield.setText(rs.getString(4));
    kebelefield.setText(rs.getString(7));
    cityfield.setText(rs.getString(8));
    zonefield.setText(rs.getString(9));
    genderfield.setText(rs.getString(10));
    searchfield.setEditable(false);
    
    
}else{
    JOptionPane.showMessageDialog(null, "Contact number doesnot exist");
}
}catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_searchfieldActionPerformed

    /**
     * @param args the comm
     * 
     * 
     *  and line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel cityy;
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JLabel contactt;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaill;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JTextField genderfield;
    private javax.swing.JTextField hnfield;
    private javax.swing.JLabel homenumberr;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kebelee;
    private javax.swing.JTextField kebelefield;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mainbadge;
    private javax.swing.JTextField middlenamefield;
    private javax.swing.JLabel namefirst;
    private javax.swing.JLabel namelast;
    private javax.swing.JLabel namemiddle;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel zonee;
    private javax.swing.JTextField zonefield;
    // End of variables declaration//GEN-END:variables
}
