

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class ManageEmployee extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public ManageEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        mainbadge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstnamel = new javax.swing.JLabel();
        middlenamel = new javax.swing.JLabel();
        lastnamel = new javax.swing.JLabel();
        positionl = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        middlenamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        positionfield = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        contactl = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        contactfield = new javax.swing.JTextField();
        genderl = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        newpositionl = new javax.swing.JLabel();
        newpositionfield = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        homenumberl = new javax.swing.JLabel();
        kebelel = new javax.swing.JLabel();
        cityl = new javax.swing.JLabel();
        zonel = new javax.swing.JLabel();
        homenumberfield = new javax.swing.JTextField();
        kebelefield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        zonefield = new javax.swing.JTextField();
        emaill = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        passwordl = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        resetbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add customer.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setUndecorated(true);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainbadge.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainbadge.setText("Manage Employee");
        getContentPane().add(mainbadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 420, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        firstnamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnamel.setText("First Name");
        getContentPane().add(firstnamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        middlenamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        middlenamel.setText("Middle Name");
        getContentPane().add(middlenamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        lastnamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnamel.setText("Last Name");
        getContentPane().add(lastnamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        positionl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        positionl.setText("Position");
        getContentPane().add(positionl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 60, -1));

        firstnamefield.setForeground(new java.awt.Color(153, 153, 153));
        firstnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusLost(evt);
            }
        });
        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 277, -1));

        middlenamefield.setForeground(new java.awt.Color(153, 153, 153));
        middlenamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        middlenamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusLost(evt);
            }
        });
        middlenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(middlenamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 277, -1));

        lastnamefield.setForeground(new java.awt.Color(153, 153, 153));
        lastnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusLost(evt);
            }
        });
        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 277, -1));

        positionfield.setForeground(new java.awt.Color(153, 153, 153));
        positionfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        positionfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                positionfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                positionfieldFocusLost(evt);
            }
        });
        positionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionfieldActionPerformed(evt);
            }
        });
        getContentPane().add(positionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 277, -1));

        updatebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 70, -1));

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/permission.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        contactl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactl.setText("Contact ");
        getContentPane().add(contactl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 60, 20));

        searchbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 100, 30));

        contactfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 250, -1));

        genderl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderl.setText("Gender");
        getContentPane().add(genderl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 50, -1));

        genderfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        genderfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderfieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 277, -1));

        newpositionl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newpositionl.setText("New Position");
        getContentPane().add(newpositionl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 100, -1));

        newpositionfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Inspector", "Officer" }));
        newpositionfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(newpositionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 280, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        homenumberl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homenumberl.setText("Home Number");
        getContentPane().add(homenumberl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        kebelel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kebelel.setText("Kebele");
        getContentPane().add(kebelel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));

        cityl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityl.setText("City");
        getContentPane().add(cityl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        zonel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        zonel.setText("Zone");
        getContentPane().add(zonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, -1, -1));

        homenumberfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(homenumberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 200, -1));

        kebelefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kebelefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebelefieldActionPerformed(evt);
            }
        });
        getContentPane().add(kebelefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 200, -1));

        cityfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 200, -1));

        zonefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(zonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 200, -1));

        emaill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaill.setText("Email");
        getContentPane().add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        emailfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 277, -1));

        passwordl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordl.setText("Password");
        getContentPane().add(passwordl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        passwordfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 277, -1));

        resetbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 60, -1));

        deletebutton.setBackground(new java.awt.Color(255, 51, 51));
        deletebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 60, -1));

        jPanel3.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed

    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed

    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void positionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionfieldActionPerformed

    private void firstnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusGained
                if(firstnamefield.getText().equals("Enter First Name")){
            firstnamefield.setText("");
        firstnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_firstnamefieldFocusGained

    private void firstnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusLost
                 if(firstnamefield.getText().equals("")){
            firstnamefield.setText("Enter First Name");
        firstnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_firstnamefieldFocusLost

    private void middlenamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusGained
        // TODO add your handling code here:
        if(middlenamefield.getText().equals("Enter Middle Name")){
            middlenamefield.setText("");
        middlenamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_middlenamefieldFocusGained

    private void middlenamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusLost
        // TODO add your handling code here:                 
        if(middlenamefield.getText().equals("")){
            middlenamefield.setText("Enter Middle Name");
        middlenamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_middlenamefieldFocusLost

    private void lastnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusGained
        // TODO add your handling code here:
        if(lastnamefield.getText().equals("Enter Last Name")){
            lastnamefield.setText("");
        lastnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_lastnamefieldFocusGained

    private void lastnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusLost
        // TODO add your handling code here:
                         if(lastnamefield.getText().equals("")){
            lastnamefield.setText("Enter Last Name");
        lastnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_lastnamefieldFocusLost

    private void positionfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionfieldFocusGained
        // TODO add your handling code here:
        if(positionfield.getText().equals("example@aait.com")){
            positionfield.setText("");
        positionfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_positionfieldFocusGained

    private void positionfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionfieldFocusLost
        // TODO add your handling code here:
                         if(positionfield.getText().equals("")){
            positionfield.setText("example@aait.com");
        positionfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_positionfieldFocusLost

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
setVisible(false);
new ManageEmployee().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void middlenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenamefieldActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
String contact = contactfield.getText();
String firstname = firstnamefield.getText();
String middlename = middlenamefield.getText();
String lastname = lastnamefield.getText();
String gender = genderfield.getText();
String position = (String) newpositionfield.getSelectedItem();
String homenumber = homenumberfield.getText();
String kebele = kebelefield.getText();
String city = cityfield.getText();
String zone = zonefield.getText();
String email = emailfield.getText();
String password = passwordfield.getText();



        
try{
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update employee set firstname = '"+firstname+"',middlename = '"+middlename+"',password = '"+password+"',position = '"+position+"',lastname = '"+lastname+"',contact='"+contact+"',email='"+email+"',homenumber='"+homenumber+"',kebele='"+kebele+"',city='"+city+"',zone='"+zone+"',gender='"+gender+"' where contact='"+contact+"';");
        JOptionPane.showMessageDialog(null, "Successfully Updated");
        setVisible(false);
        new ManageEmployee().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }      
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
String contact = contactfield.getText();
try{
Connection con = ConnectionProvider.getCon();
Statement st = con.createStatement();
ResultSet rs = st.executeQuery("select * from employee where contact = '"+contact+"'");
if (rs.next()){
    firstnamefield.setText(rs.getString(3));
    middlenamefield.setText(rs.getString(4));
    lastnamefield.setText(rs.getString(5));
    positionfield.setText(rs.getString(12));
    genderfield.setText(rs.getString(6));
    homenumberfield.setText(rs.getString(8));
    kebelefield.setText(rs.getString(9));
    cityfield.setText(rs.getString(10));
    zonefield.setText(rs.getString(11));
    emailfield.setText(rs.getString(1));
    passwordfield.setText(rs.getString(2));
    
    
    
    
}else{
    JOptionPane.showMessageDialog(null, "Contact number doesnot exist");
}
}catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_contactfieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
this.contactfieldActionPerformed(evt);       // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void genderfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderfieldActionPerformed

    private void kebelefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebelefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebelefieldActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
int a = JOptionPane.showConfirmDialog(null,"Do you want to delete","Select", JOptionPane.YES_NO_OPTION);
if(a==0){
        String contact = contactfield.getText();
try{
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from employee where contact='"+contact+"';");
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
        setVisible(false);
        new ManageEmployee().setVisible(true);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        } }           // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the comm
     * 
     * 
     *  and line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel cityl;
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactl;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaill;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel firstnamel;
    private javax.swing.JTextField genderfield;
    private javax.swing.JLabel genderl;
    private javax.swing.JTextField homenumberfield;
    private javax.swing.JLabel homenumberl;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kebelefield;
    private javax.swing.JLabel kebelel;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lastnamel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mainbadge;
    private javax.swing.JTextField middlenamefield;
    private javax.swing.JLabel middlenamel;
    private javax.swing.JComboBox<String> newpositionfield;
    private javax.swing.JLabel newpositionl;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JLabel passwordl;
    private javax.swing.JTextField positionfield;
    private javax.swing.JLabel positionl;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField zonefield;
    private javax.swing.JLabel zonel;
    // End of variables declaration//GEN-END:variables
}
