

import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class NewRecord extends javax.swing.JFrame {

    /**
     * Creates new form NewRecord
     */
    public NewRecord() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainbadge = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        recordidl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        descriptinol = new javax.swing.JLabel();
        descriptionfield = new javax.swing.JTextField();
        metercountl = new javax.swing.JLabel();
        metercountfield = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        customeridl = new javax.swing.JLabel();
        customeridfield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainbadge.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainbadge.setText("Add Record");
        getContentPane().add(mainbadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 273, -1));

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add rec.png"))); // NOI18N
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, -1));

        recordidl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recordidl.setText("Record ID");
        getContentPane().add(recordidl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 95, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 37, -1));

        descriptinol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptinol.setText("Description");
        getContentPane().add(descriptinol, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 92, -1));

        descriptionfield.setForeground(new java.awt.Color(153, 153, 153));
        descriptionfield.setText("Enter Description");
        descriptionfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descriptionfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descriptionfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionfieldFocusLost(evt);
            }
        });
        descriptionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionfieldActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 267, -1));

        metercountl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        metercountl.setText("Meter Count");
        getContentPane().add(metercountl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 92, -1));

        metercountfield.setForeground(new java.awt.Color(153, 153, 153));
        metercountfield.setText("Enter Current Meter Count");
        metercountfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        metercountfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                metercountfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                metercountfieldFocusLost(evt);
            }
        });
        metercountfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metercountfieldActionPerformed(evt);
            }
        });
        getContentPane().add(metercountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 267, -1));

        savebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        savebutton.setText("Save");
        savebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 60, -1));

        resetbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 60, -1));

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, 60, -1));

        customeridl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customeridl.setText("Customer ID");
        getContentPane().add(customeridl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        customeridfield.setForeground(new java.awt.Color(153, 153, 153));
        customeridfield.setText("Enter customer Id");
        customeridfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customeridfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customeridfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customeridfieldFocusLost(evt);
            }
        });
        customeridfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridfieldActionPerformed(evt);
            }
        });
        getContentPane().add(customeridfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 270, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        jPanel2.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       try{
           Connection con2 = ConnectionProvider.getCon();
           Statement st2 = con2.createStatement();
           ResultSet rs2 = st2.executeQuery("select max(rid) from record");
           if(rs2.next()){
               int id = rs2.getInt(1);
               id = id + 1;
               String str = String.valueOf(id);
               jLabel4.setText(str);
           }
           else{
               jLabel4.setText("1");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_formComponentShown

    private void metercountfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metercountfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metercountfieldActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void metercountfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_metercountfieldFocusGained
       if (metercountfield.getText().equals("Enter Current Meter Count")){
           metercountfield.setText("");
           metercountfield.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_metercountfieldFocusGained

    private void metercountfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_metercountfieldFocusLost
       if (metercountfield.getText().equals("")){
           metercountfield.setText("Enter Current Meter Count");
           metercountfield.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_metercountfieldFocusLost

    private void descriptionfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionfieldFocusGained
        // TODO add your handling code here:
        if (descriptionfield.getText().equals("Enter Description")){
           descriptionfield.setText("");
           descriptionfield.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_descriptionfieldFocusGained

    private void descriptionfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionfieldFocusLost
              if (metercountfield.getText().equals("")){
           metercountfield.setText("Enter Description");
           metercountfield.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_descriptionfieldFocusLost

    private void customeridfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customeridfieldFocusGained
        if (customeridfield.getText().equals("Enter customer Id")){
           customeridfield.setText("");
           customeridfield.setForeground(new Color(0,0,0));
       }
    }//GEN-LAST:event_customeridfieldFocusGained

    private void customeridfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customeridfieldFocusLost
        // TODO add your handling code here:
        if (customeridfield.getText().equals("")){
           customeridfield.setText("Enter customer Id");
           customeridfield.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_customeridfieldFocusLost

    private void customeridfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridfieldActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        String rid = jLabel4.getText();
        String cid = customeridfield.getText();
        String mcount = metercountfield.getText();
        String description = descriptionfield.getText();
        String status = "Unpaid";
         try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
               LocalDateTime now = LocalDateTime.now();
           st.executeUpdate("insert into record values('"+rid+"','"+cid+"','"+mcount+"','"+description+"','"+status+"','"+dtf.format(now)+"')");
           JOptionPane.showMessageDialog(null, "Successfull inserted");
           setVisible(false);
           new NewRecord().setVisible(true);
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e.getMessage());
         }
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void descriptionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionfieldActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
setVisible(false);
new NewRecord().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField customeridfield;
    private javax.swing.JLabel customeridl;
    private javax.swing.JLabel descriptinol;
    private javax.swing.JTextField descriptionfield;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel log;
    private javax.swing.JLabel mainbadge;
    private javax.swing.JTextField metercountfield;
    private javax.swing.JLabel metercountl;
    private javax.swing.JLabel recordidl;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
}
