
import javax.swing.JTable;
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class Profile extends javax.swing.JFrame {
    String email;
private static String semail;
    /**
     * Creates new form Profile
     */
    public Profile(String email) {
        this.email = email;
        this.semail  = email;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilelabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        emaill = new javax.swing.JLabel();
        genderl = new javax.swing.JLabel();
        contactl = new javax.swing.JLabel();
        positionl = new javax.swing.JLabel();
        homenumberl = new javax.swing.JLabel();
        kebelel = new javax.swing.JLabel();
        cityl = new javax.swing.JLabel();
        zonel = new javax.swing.JLabel();
        addressl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        emaillabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        homenumberlabel = new javax.swing.JLabel();
        kebelelabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        zonelabel = new javax.swing.JLabel();
        positionlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilelabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        profilelabel.setText("Profile");
        getContentPane().add(profilelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 590, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user profile.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        closebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, -1, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        emaill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emaill.setText("Email");
        getContentPane().add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        genderl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        genderl.setText("Gender");
        getContentPane().add(genderl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        contactl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactl.setText("Contact");
        getContentPane().add(contactl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        positionl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        positionl.setText("Position");
        getContentPane().add(positionl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        homenumberl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        homenumberl.setText("Home Number");
        getContentPane().add(homenumberl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        kebelel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kebelel.setText("Kebele");
        getContentPane().add(kebelel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        cityl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cityl.setText("City");
        getContentPane().add(cityl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        zonel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        zonel.setText("Zone");
        getContentPane().add(zonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        addressl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addressl.setText("Address");
        getContentPane().add(addressl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 900, 10));

        emaillabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        emaillabel.setText("jLabel12");
        getContentPane().add(emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 290, -1));

        genderlabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        genderlabel.setText("jLabel13");
        getContentPane().add(genderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 270, -1));

        contactlabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        contactlabel.setText("jLabel14");
        getContentPane().add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 270, -1));

        homenumberlabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        homenumberlabel.setText("jLabel15");
        getContentPane().add(homenumberlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 200, -1));

        kebelelabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        kebelelabel.setText("jLabel16");
        getContentPane().add(kebelelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 200, -1));

        citylabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        citylabel.setText("jLabel17");
        getContentPane().add(citylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 140, -1));

        zonelabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        zonelabel.setText("jLabel18");
        getContentPane().add(zonelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 140, -1));

        positionlabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        positionlabel.setText("jLabel19");
        getContentPane().add(positionlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 130, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

try{
Connection con = ConnectionProvider.getCon();
Statement st = con.createStatement();
ResultSet rs = st.executeQuery("select * from employee where email = '"+email+"'");
if (rs.next()){
    profilelabel.setText(rs.getString(3)+ "  "+rs.getString(4)+ "  " + rs.getString(5));
    emaillabel.setText(rs.getString(1));
    genderlabel.setText(rs.getString(6));
    contactlabel.setText(rs.getString(7));
    homenumberlabel.setText(rs.getString(8));
   kebelelabel.setText(rs.getString(9));
    citylabel.setText(rs.getString(10));
    zonelabel.setText(rs.getString(11));
    positionlabel.setText(rs.getString(12));

    
}else{
    JOptionPane.showMessageDialog(null, "Contact Your manager");
}
}catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile(semail).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressl;
    private javax.swing.JLabel cityl;
    private javax.swing.JLabel citylabel;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel contactl;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JLabel emaill;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel genderl;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel homenumberl;
    private javax.swing.JLabel homenumberlabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kebelel;
    private javax.swing.JLabel kebelelabel;
    private javax.swing.JLabel positionl;
    private javax.swing.JLabel positionlabel;
    private javax.swing.JLabel profilelabel;
    private javax.swing.JLabel zonel;
    private javax.swing.JLabel zonelabel;
    // End of variables declaration//GEN-END:variables
}
