
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class UpdateRecord extends javax.swing.JFrame {

    /**
     * Creates new form UpdateRecord
     */
    public UpdateRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAintitl = new javax.swing.JLabel();
        mainlogo = new javax.swing.JLabel();
        recordid = new javax.swing.JLabel();
        recordidfield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        customerid = new javax.swing.JLabel();
        customeridfield = new javax.swing.JTextField();
        metercount = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        metercountfield = new javax.swing.JTextField();
        descriptionfield = new javax.swing.JTextField();
        statusfield = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAintitl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MAintitl.setText("Update Record");
        getContentPane().add(MAintitl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 296, -1));

        mainlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update data.png"))); // NOI18N
        getContentPane().add(mainlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, -1));

        recordid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recordid.setText("Record Id");
        getContentPane().add(recordid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        recordidfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        recordidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordidfieldActionPerformed(evt);
            }
        });
        getContentPane().add(recordidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 242, -1));

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 80, -1));

        customerid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerid.setText("Customer Id");
        getContentPane().add(customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        customeridfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customeridfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridfieldActionPerformed(evt);
            }
        });
        getContentPane().add(customeridfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 243, -1));

        metercount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        metercount.setText("Meter Count");
        getContentPane().add(metercount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 96, -1));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setText("Status");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 65, -1));

        metercountfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        metercountfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metercountfieldActionPerformed(evt);
            }
        });
        getContentPane().add(metercountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 243, -1));

        descriptionfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descriptionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionfieldActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 243, 93));

        statusfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusfieldActionPerformed(evt);
            }
        });
        getContentPane().add(statusfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 243, -1));

        updatebutton.setText("Update");
        updatebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 60, -1));

        resetbutton.setText("Reset");
        resetbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 70, -1));

        closebutton.setText("Close");
        closebutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 70, 20));

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 100, 20));

        datefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        datefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datefieldActionPerformed(evt);
            }
        });
        getContentPane().add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 243, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        jPanel2.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
setVisible(false);
new UpdateRecord().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        String rid = recordidfield.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from record where rid='"+rid+"'");
            if(rs.next()){
                customeridfield.setText(rs.getString(2));
                metercountfield.setText(rs.getString(3));
                descriptionfield.setText(rs.getString(4));
                statusfield.setText(rs.getString(5));
                datefield.setText(rs.getString(6));
                
                recordidfield.setEditable(false);
                datefield.setEditable(false);
                
            }else{
                JOptionPane.showMessageDialog(null,"Record id doesnot exist");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void customeridfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridfieldActionPerformed

    private void metercountfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metercountfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metercountfieldActionPerformed

    private void descriptionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionfieldActionPerformed

    private void statusfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusfieldActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        String rid = recordidfield.getText();
        String cid = customeridfield.getText();
        String mcount = metercountfield.getText();
        String description = descriptionfield.getText();
        String status = statusfield.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();

            st.executeUpdate("update record set rid ='"+rid+"',cid = '"+cid+"',mcount = '"+mcount+"',description='"+description+"',status='"+status+"' where rid='"+rid+"'");
        JOptionPane.showMessageDialog(null,"successfully updated");
        setVisible(false);
       new UpdateRecord().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void datefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefieldActionPerformed

    private void recordidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordidfieldActionPerformed
this.searchbuttonActionPerformed(evt);    // TODO add your handling code here:
    }//GEN-LAST:event_recordidfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MAintitl;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel customerid;
    private javax.swing.JTextField customeridfield;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datefield;
    private javax.swing.JLabel description;
    private javax.swing.JTextField descriptionfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mainlogo;
    private javax.swing.JLabel metercount;
    private javax.swing.JTextField metercountfield;
    private javax.swing.JLabel recordid;
    private javax.swing.JTextField recordidfield;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusfield;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
