

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author semha
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public UpdateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        mainbadge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstnamel = new javax.swing.JLabel();
        middlenamel = new javax.swing.JLabel();
        lastnamel = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        kebelel = new javax.swing.JLabel();
        conatctl = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        middlenamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        cityl = new javax.swing.JLabel();
        zonel = new javax.swing.JLabel();
        homenumberl = new javax.swing.JLabel();
        homenumberfield = new javax.swing.JTextField();
        kebelefield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        zonefied = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        contactl = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        genderl = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add customer.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 36));
        setUndecorated(true);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainbadge.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainbadge.setText("Update Customer");
        getContentPane().add(mainbadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 450, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        firstnamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnamel.setText("First Name");
        getContentPane().add(firstnamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        middlenamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        middlenamel.setText("Middle Name");
        getContentPane().add(middlenamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        lastnamel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnamel.setText("Last Name");
        getContentPane().add(lastnamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("E-mail");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 50, -1));

        kebelel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kebelel.setText("Kebele");
        getContentPane().add(kebelel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 55, -1));

        conatctl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        conatctl.setText("Contact");
        getContentPane().add(conatctl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        firstnamefield.setForeground(new java.awt.Color(153, 153, 153));
        firstnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusLost(evt);
            }
        });
        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 277, -1));

        middlenamefield.setForeground(new java.awt.Color(153, 153, 153));
        middlenamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        middlenamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middlenamefieldFocusLost(evt);
            }
        });
        middlenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(middlenamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 277, -1));

        lastnamefield.setForeground(new java.awt.Color(153, 153, 153));
        lastnamefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnamefieldFocusLost(evt);
            }
        });
        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 277, -1));

        emailfield.setForeground(new java.awt.Color(153, 153, 153));
        emailfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfieldFocusLost(evt);
            }
        });
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 277, -1));

        contactfield.setForeground(new java.awt.Color(153, 153, 153));
        contactfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactfieldFocusLost(evt);
            }
        });
        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 277, -1));

        updatebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, -1, -1));

        resetbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, -1, -1));

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, -1, -1));

        cityl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityl.setText("City");
        getContentPane().add(cityl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 43, -1));

        zonel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        zonel.setText("Zone");
        getContentPane().add(zonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 43, -1));

        homenumberl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homenumberl.setText("Home Number");
        getContentPane().add(homenumberl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        homenumberfield.setForeground(new java.awt.Color(153, 153, 153));
        homenumberfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homenumberfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homenumberfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homenumberfieldFocusLost(evt);
            }
        });
        homenumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homenumberfieldActionPerformed(evt);
            }
        });
        getContentPane().add(homenumberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 277, -1));

        kebelefield.setForeground(new java.awt.Color(153, 153, 153));
        kebelefield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kebelefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kebelefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kebelefieldFocusLost(evt);
            }
        });
        kebelefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebelefieldActionPerformed(evt);
            }
        });
        getContentPane().add(kebelefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 277, -1));

        cityfield.setForeground(new java.awt.Color(153, 153, 153));
        cityfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityfieldFocusLost(evt);
            }
        });
        cityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 277, -1));

        zonefied.setForeground(new java.awt.Color(153, 153, 153));
        zonefied.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        zonefied.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zonefiedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zonefiedFocusLost(evt);
            }
        });
        zonefied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonefiedActionPerformed(evt);
            }
        });
        getContentPane().add(zonefied, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 277, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile update.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 90));

        contactl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactl.setText("Contact ");
        getContentPane().add(contactl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));

        searchfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 250, 30));

        genderl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderl.setText("Gender");
        getContentPane().add(genderl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 50, -1));

        genderfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        genderfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderfieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 277, -1));

        jPanel1.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jPanel2.setBackground(new java.awt.Color(110, 190, 242));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1090, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed

    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed

    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactfieldActionPerformed

    private void kebelefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebelefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebelefieldActionPerformed

    private void zonefiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonefiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonefiedActionPerformed

    private void firstnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusGained
                if(firstnamefield.getText().equals("Enter First Name")){
            firstnamefield.setText("");
        firstnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_firstnamefieldFocusGained

    private void firstnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusLost
                 if(firstnamefield.getText().equals("")){
            firstnamefield.setText("Enter First Name");
        firstnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_firstnamefieldFocusLost

    private void middlenamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusGained
        // TODO add your handling code here:
        if(middlenamefield.getText().equals("Enter Middle Name")){
            middlenamefield.setText("");
        middlenamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_middlenamefieldFocusGained

    private void middlenamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenamefieldFocusLost
        // TODO add your handling code here:                 
        if(middlenamefield.getText().equals("")){
            middlenamefield.setText("Enter Middle Name");
        middlenamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_middlenamefieldFocusLost

    private void lastnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusGained
        // TODO add your handling code here:
        if(lastnamefield.getText().equals("Enter Last Name")){
            lastnamefield.setText("");
        lastnamefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_lastnamefieldFocusGained

    private void lastnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnamefieldFocusLost
        // TODO add your handling code here:
                         if(lastnamefield.getText().equals("")){
            lastnamefield.setText("Enter Last Name");
        lastnamefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_lastnamefieldFocusLost

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        // TODO add your handling code here:
        if(emailfield.getText().equals("example@aait.com")){
            emailfield.setText("");
        emailfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emailfieldFocusGained

    private void emailfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusLost
        // TODO add your handling code here:
                         if(emailfield.getText().equals("")){
            emailfield.setText("example@aait.com");
        emailfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailfieldFocusLost

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        // TODO add your handling code here:
        if(contactfield.getText().equals("+251111111111")){
            contactfield.setText("");
        contactfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_contactfieldFocusGained

    private void contactfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusLost
        // TODO add your handling code here:
                         if(contactfield.getText().equals("")){
            contactfield.setText("+251111111111");
        contactfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_contactfieldFocusLost

    private void homenumberfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homenumberfieldFocusGained
        // TODO add your handling code here:
        if(homenumberfield.getText().equals("225")){
            homenumberfield.setText("");
        homenumberfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_homenumberfieldFocusGained

    private void homenumberfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homenumberfieldFocusLost
        // TODO add your handling code here:
                         if(homenumberfield.getText().equals("")){
            homenumberfield.setText("225");
        homenumberfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_homenumberfieldFocusLost

    private void kebelefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kebelefieldFocusGained
        // TODO add your handling code here:
        if(kebelefield.getText().equals("05")){
            kebelefield.setText("");
        kebelefield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_kebelefieldFocusGained

    private void kebelefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kebelefieldFocusLost
        // TODO add your handling code here:
                         if(kebelefield.getText().equals("")){
            kebelefield.setText("05");
        kebelefield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_kebelefieldFocusLost

    private void cityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusGained
        // TODO add your handling code here:
        if(cityfield.getText().equals("Hawassa")){
            cityfield.setText("");
        cityfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cityfieldFocusGained

    private void cityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusLost
        // TODO add your handling code here:
                         if(cityfield.getText().equals("")){
            cityfield.setText("Hawassa");
        cityfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_cityfieldFocusLost

    private void zonefiedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zonefiedFocusGained
        // TODO add your handling code here:
        if(zonefied.getText().equals("Sidama")){
            zonefied.setText("");
        zonefied.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_zonefiedFocusGained

    private void zonefiedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zonefiedFocusLost
        // TODO add your handling code here:
                         if(zonefied.getText().equals("")){
            zonefied.setText("Sidama");
        zonefied.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_zonefiedFocusLost

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
setVisible(false);
new UpdateCustomer().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void middlenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenamefieldActionPerformed

    private void homenumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homenumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homenumberfieldActionPerformed

    private void cityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityfieldActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
String firstname = firstnamefield.getText();
        String middlename = middlenamefield.getText();
        String lastname = lastnamefield.getText();
        String email = emailfield.getText();
        String contact = contactfield.getText();
        String homenumber = homenumberfield.getText();
        String kebele = kebelefield.getText();
        String city = cityfield.getText();
        String zone = zonefied.getText();
        String gender = genderfield.getText();
        
try{
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update customer set firstname = '"+firstname+"',middlename = '"+middlename+"',lastname = '"+lastname+"',contactnumber='"+contact+"',email='"+email+"',homenumber='"+homenumber+"',kebele='"+kebele+"',city='"+city+"',zone='"+zone+"',gender='"+gender+"' where contactnumber='"+contact+"';");
        JOptionPane.showConfirmDialog(null, "Successfully Updated");
        setVisible(false);
        new UpdateCustomer().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }      
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
String contact = searchfield.getText();
try{
Connection con = ConnectionProvider.getCon();
Statement st = con.createStatement();
ResultSet rs = st.executeQuery("select * from customer where contactnumber = '"+contact+"'");
if (rs.next()){
    firstnamefield.setText(rs.getString(1));
    middlenamefield.setText(rs.getString(2));
    lastnamefield.setText(rs.getString(3));
    emailfield.setText(rs.getString(5));
    homenumberfield.setText(rs.getString(6));
    contactfield.setText(rs.getString(4));
    kebelefield.setText(rs.getString(7));
    cityfield.setText(rs.getString(8));
    zonefied.setText(rs.getString(9));
    genderfield.setText(rs.getString(10));
    searchfield.setEditable(false);
    
    
}else{
    JOptionPane.showMessageDialog(null, "Contact number doesnot exist");
}
}catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
this.searchfieldActionPerformed(evt);       // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void genderfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderfieldActionPerformed

    /**
     * @param args the comm
     * 
     * 
     *  and line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel cityl;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel conatctl;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactl;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel firstnamel;
    private javax.swing.JTextField genderfield;
    private javax.swing.JLabel genderl;
    private javax.swing.JTextField homenumberfield;
    private javax.swing.JLabel homenumberl;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kebelefield;
    private javax.swing.JLabel kebelel;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lastnamel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mainbadge;
    private javax.swing.JTextField middlenamefield;
    private javax.swing.JLabel middlenamel;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField zonefied;
    private javax.swing.JLabel zonel;
    // End of variables declaration//GEN-END:variables
}
